# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtube_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modify Date'),
        ),
    ]
